service:
  name: budgetzen-web-v2

useDotEnv: true

myNextAppplication:
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    domain: ['app', 'budgetzen.net']
    bucketName: budgetzen-web-v2
    bucketRegion: us-east-1
